name: nexus-mp-docker
version: '1.0.0'
summary: Nexus Mail Protocol Server (Docker)
description: |
  IMAP server for Nexus mail system.
  Docker container version.
base: core22
confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: amd64

apps:
  nexus-mp:
    command: bin/nexus-mp
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  nexus-mp:
    plugin: make
    source: .
    source-type: local
